// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
//import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SeleniumJUnitTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "/home/test/Clinica/clinica/geckodriver");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumJUnit() {
    driver.get("http://localhost:8080/clinica/");
    driver.manage().window().setSize(new Dimension(550, 705));
    driver.findElement(By.cssSelector("#menu-atendentes > .ui-menuitem-text")).click();
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("form_atendentes:cpf")).click();
    driver.findElement(By.id("form_atendentes:cpf")).sendKeys("123");
    driver.findElement(By.id("form_atendentes:nome")).click();
    driver.findElement(By.id("form_atendentes:nome")).sendKeys("Antônio");
    driver.findElement(By.cssSelector("#form_atendentes\\3A btn_salvar > .ui-button-text")).click();
    driver.findElement(By.id("menu-medicos")).click();
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("form_medicos:cpf")).click();
    driver.findElement(By.id("form_medicos:cpf")).sendKeys("456");
    driver.findElement(By.id("form_medicos:nome")).click();
    driver.findElement(By.id("form_medicos:nome")).sendKeys("João");
    driver.findElement(By.id("form_medicos:registro")).click();
    driver.findElement(By.id("form_medicos:registro")).sendKeys("456");
    driver.findElement(By.id("form_medicos:especialidade")).click();
    driver.findElement(By.id("form_medicos:especialidade")).sendKeys("Cardiologia");
    driver.findElement(By.cssSelector("#form_medicos\\3A btn_salvar > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#menu-pacientes > .ui-menuitem-text")).click();
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".ui-button-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("form_pacientes:cpf")).click();
    driver.findElement(By.id("form_pacientes:cpf")).sendKeys("789");
    driver.findElement(By.id("form_pacientes:nome")).click();
    driver.findElement(By.id("form_pacientes:nome")).sendKeys("Alberto");
    driver.findElement(By.cssSelector("#form_pacientes\\3A btn_salvar > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#menu-consultas > .ui-menuitem-text")).click();
    driver.findElement(By.cssSelector(".ui-button-text")).click();
    driver.findElement(By.cssSelector("#form_consultas\\3A btn_salvar > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#form_consultas\\3Alista\\3A 0\\3Aj_idt16 > .ui-button-text")).click();
    driver.findElement(By.id("menu-pacientes")).click();
    driver.findElement(By.cssSelector("#form_pacientes\\3Alista\\3A 0\\3Aj_idt15 > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#menu-medicos > .ui-menuitem-text")).click();
    driver.findElement(By.cssSelector("#form_medicos\\3Alista\\3A 0\\3Aj_idt17 > .ui-button-text")).click();
    driver.findElement(By.cssSelector("#menu-atendentes > .ui-menuitem-text")).click();
    driver.findElement(By.cssSelector("#form_atendentes\\3Alista\\3A 0\\3Aj_idt15 > .ui-button-text")).click();
  }
}
